/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as IngresoRouteImport } from './routes/ingreso'
import { Route as ClinicaRouteImport } from './routes/clinica'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReporteIndexRouteImport } from './routes/reporte.index'
import { Route as ReporteVideoIdRouteImport } from './routes/reporte.$videoId'
import { Route as ProcesandoVideoIdRouteImport } from './routes/procesando.$videoId'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresoRoute = IngresoRouteImport.update({
  id: '/ingreso',
  path: '/ingreso',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicaRoute = ClinicaRouteImport.update({
  id: '/clinica',
  path: '/clinica',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReporteIndexRoute = ReporteIndexRouteImport.update({
  id: '/reporte/',
  path: '/reporte/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReporteVideoIdRoute = ReporteVideoIdRouteImport.update({
  id: '/reporte/$videoId',
  path: '/reporte/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcesandoVideoIdRoute = ProcesandoVideoIdRouteImport.update({
  id: '/procesando/$videoId',
  path: '/procesando/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinica': typeof ClinicaRoute
  '/ingreso': typeof IngresoRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/registro': typeof RegistroRoute
  '/tecnologia': typeof TecnologiaRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/procesando/$videoId': typeof ProcesandoVideoIdRoute
  '/reporte/$videoId': typeof ReporteVideoIdRoute
  '/reporte/': typeof ReporteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinica': typeof ClinicaRoute
  '/ingreso': typeof IngresoRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/registro': typeof RegistroRoute
  '/tecnologia': typeof TecnologiaRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/procesando/$videoId': typeof ProcesandoVideoIdRoute
  '/reporte/$videoId': typeof ReporteVideoIdRoute
  '/reporte': typeof ReporteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinica': typeof ClinicaRoute
  '/ingreso': typeof IngresoRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/registro': typeof RegistroRoute
  '/tecnologia': typeof TecnologiaRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/procesando/$videoId': typeof ProcesandoVideoIdRoute
  '/reporte/$videoId': typeof ReporteVideoIdRoute
  '/reporte/': typeof ReporteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinica'
    | '/ingreso'
    | '/performance'
    | '/profile'
    | '/registro'
    | '/tecnologia'
    | '/upload'
    | '/videos'
    | '/procesando/$videoId'
    | '/reporte/$videoId'
    | '/reporte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinica'
    | '/ingreso'
    | '/performance'
    | '/profile'
    | '/registro'
    | '/tecnologia'
    | '/upload'
    | '/videos'
    | '/procesando/$videoId'
    | '/reporte/$videoId'
    | '/reporte'
  id:
    | '__root__'
    | '/'
    | '/clinica'
    | '/ingreso'
    | '/performance'
    | '/profile'
    | '/registro'
    | '/tecnologia'
    | '/upload'
    | '/videos'
    | '/procesando/$videoId'
    | '/reporte/$videoId'
    | '/reporte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicaRoute: typeof ClinicaRoute
  IngresoRoute: typeof IngresoRoute
  PerformanceRoute: typeof PerformanceRoute
  ProfileRoute: typeof ProfileRoute
  RegistroRoute: typeof RegistroRoute
  TecnologiaRoute: typeof TecnologiaRoute
  UploadRoute: typeof UploadRoute
  VideosRoute: typeof VideosRoute
  ProcesandoVideoIdRoute: typeof ProcesandoVideoIdRoute
  ReporteVideoIdRoute: typeof ReporteVideoIdRoute
  ReporteIndexRoute: typeof ReporteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingreso': {
      id: '/ingreso'
      path: '/ingreso'
      fullPath: '/ingreso'
      preLoaderRoute: typeof IngresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinica': {
      id: '/clinica'
      path: '/clinica'
      fullPath: '/clinica'
      preLoaderRoute: typeof ClinicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporte/': {
      id: '/reporte/'
      path: '/reporte'
      fullPath: '/reporte/'
      preLoaderRoute: typeof ReporteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporte/$videoId': {
      id: '/reporte/$videoId'
      path: '/reporte/$videoId'
      fullPath: '/reporte/$videoId'
      preLoaderRoute: typeof ReporteVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procesando/$videoId': {
      id: '/procesando/$videoId'
      path: '/procesando/$videoId'
      fullPath: '/procesando/$videoId'
      preLoaderRoute: typeof ProcesandoVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicaRoute: ClinicaRoute,
  IngresoRoute: IngresoRoute,
  PerformanceRoute: PerformanceRoute,
  ProfileRoute: ProfileRoute,
  RegistroRoute: RegistroRoute,
  TecnologiaRoute: TecnologiaRoute,
  UploadRoute: UploadRoute,
  VideosRoute: VideosRoute,
  ProcesandoVideoIdRoute: ProcesandoVideoIdRoute,
  ReporteVideoIdRoute: ReporteVideoIdRoute,
  ReporteIndexRoute: ReporteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
